name: flutter_common
description: A collection of common Flutter widgets, utilities, and extensions.
version: 1.0.20
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  intl: ^0.20.2
  dio: ^5.4.1
  flutter_markdown: ^0.7.7
  equatable: ^2.0.5
  version: ^3.0.2
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  printing: ^5.11.1
  pdf: ^3.10.7
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  google_mobile_ads: ^6.0.0
  mcp_llm: ^1.0.0
  mcp_client: ^1.0.0
  mcp_server: ^1.0.2
  uuid: ^4.3.3
  easy_localization: ^3.0.7+1
  permission_handler: ^12.0.1
  flutter_contacts: ^1.1.9+2
  infinite_scroll_pagination: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/translations/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

  uses-material-design: true
